package ch.it4user.fintube.web;
import ch.it4user.fintube.core.*; import ch.it4user.fintube.media.*; import ch.it4user.fintube.integration.YouTubeSyncService; import ch.it4user.fintube.integration.JellyfinSyncService;
import org.springframework.beans.factory.annotation.Value; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import org.springframework.web.server.ResponseStatusException; import jakarta.servlet.http.*;
import java.nio.file.*; import java.sql.*; import java.net.URI; import java.net.URLEncoder; import java.net.http.HttpClient; import java.net.http.HttpRequest; import java.net.http.HttpResponse; import java.util.*; import java.io.*;
@RestController @RequestMapping("/api") public class ApiController {
 final Database db; final AuthService auth; final MediaSourceService sources; final FragmentManager fragments; final BackgroundFillService filler; final YouTubeSyncService syncer; final JellyfinSyncService jellyfin; final AuditLogger audit;
 @Value("${fintube.cookie-secure:false}") boolean cookieSecure;
 ApiController(Database d,AuthService a,MediaSourceService s,FragmentManager f,BackgroundFillService b,YouTubeSyncService y,JellyfinSyncService j,AuditLogger l){db=d;auth=a;sources=s;fragments=f;filler=b;syncer=y;jellyfin=j;audit=l;}
 AuthService.Principal user(HttpServletRequest r){try{var u=auth.current(r);if(u==null)throw new ResponseStatusException(HttpStatus.UNAUTHORIZED);return u;}catch(SQLException e){throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR);}}
 AuthService.Principal admin(HttpServletRequest r){var u=user(r);if(!u.admin())throw new ResponseStatusException(HttpStatus.FORBIDDEN);return u;}
 @PostMapping("/auth/register") Map<String,Object> register(@RequestBody Map<String,String>b,HttpServletResponse res)throws Exception{String n=req(b,"username");String p=req(b,"password");if(!n.matches("[A-Za-z0-9_.-]{3,48}")||p.length()<12)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"username or password does not meet policy");String slug=auth.slug(n);try(Connection c=db.open();PreparedStatement x=c.prepareStatement("INSERT INTO users(username,email,password_hash,role,filesystem_slug,created_at,updated_at) VALUES(?,?,?,?,?,?,?)",Statement.RETURN_GENERATED_KEYS)){x.setString(1,n);x.setString(2,b.get("email"));x.setString(3,auth.hash(p));x.setString(4,"USER");x.setString(5,slug);x.setString(6,Database.now());x.setString(7,Database.now());x.executeUpdate();long id=x.getGeneratedKeys().getLong(1);Files.createDirectories(db.usersRoot.resolve(slug));cookie(res,auth.login(id));audit.event("USER_REGISTERED",Map.of("userId",id));return Map.of("username",n,"role","USER");}catch(SQLException e){throw new ResponseStatusException(HttpStatus.CONFLICT,"username already exists");}}
 @PostMapping("/auth/login") Map<String,Object> login(@RequestBody Map<String,String>b,HttpServletResponse res)throws Exception{try(Connection c=db.open();PreparedStatement p=c.prepareStatement("SELECT id,password_hash,role FROM users WHERE username=?")){p.setString(1,req(b,"username"));ResultSet x=p.executeQuery();if(!x.next()||!auth.matches(req(b,"password"),x.getString(2))){audit.event("USER_LOGIN_FAILED",Map.of("username",b.getOrDefault("username","")));throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"invalid credentials");}long userId=x.getLong(1);cookie(res,auth.login(userId));audit.event("USER_LOGIN",Map.of("userId",userId,"role",x.getString(3)));return Map.of("role",x.getString(3));}}
 @PostMapping("/auth/logout") void logout(HttpServletRequest r,HttpServletResponse res)throws Exception{var u=user(r);auth.logout(r);clearCookie(res);audit.event("USER_LOGOUT",Map.of("userId",u.id()));}
 @GetMapping("/me") Map<String,Object> me(HttpServletRequest r){var u=user(r);return Map.of("id",u.id(),"username",u.username(),"role",u.role(),"filesystemSlug",u.slug());}
 @PostMapping("/me/change-password") void password(HttpServletRequest r,@RequestBody Map<String,String>b)throws Exception{var u=user(r);String old=req(b,"oldPassword"),next=req(b,"newPassword");if(next.length()<12)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"password must be at least 12 characters");try(Connection c=db.open();PreparedStatement q=c.prepareStatement("SELECT password_hash FROM users WHERE id=?")){q.setLong(1,u.id());ResultSet z=q.executeQuery();if(!z.next()||!auth.matches(old,z.getString(1)))throw new ResponseStatusException(HttpStatus.UNAUTHORIZED);try(PreparedStatement p=c.prepareStatement("UPDATE users SET password_hash=?,updated_at=? WHERE id=?")){p.setString(1,auth.hash(next));p.setString(2,Database.now());p.setLong(3,u.id());p.executeUpdate();}}audit.event("PASSWORD_CHANGED",Map.of("userId",u.id()));}
 @GetMapping("/subscriptions") List<Map<String,Object>> subscriptions(HttpServletRequest r)throws Exception{var u=user(r);return rows("SELECT s.id,c.channel_id,c.name,c.url,s.enabled,s.last_checked_at FROM youtube_subscriptions s JOIN youtube_channels c ON c.channel_id=s.channel_id WHERE s.user_id=? ORDER BY c.name",u.id());}
 @PostMapping("/subscriptions") Map<String,Object> addSub(HttpServletRequest r,@RequestBody Map<String,String>b)throws Exception{var u=user(r);Channel ch=resolve(req(b,"channel"));try(Connection c=db.open();PreparedStatement a=c.prepareStatement("INSERT INTO youtube_channels(channel_id,name,url,updated_at) VALUES(?,?,?,?) ON CONFLICT(channel_id) DO UPDATE SET name=excluded.name,url=excluded.url,updated_at=excluded.updated_at")){a.setString(1,ch.id);a.setString(2,ch.name);a.setString(3,ch.url);a.setString(4,Database.now());a.executeUpdate();try(PreparedStatement p=c.prepareStatement("INSERT INTO youtube_subscriptions(user_id,channel_id,created_at) VALUES(?,?,?)")){p.setLong(1,u.id());p.setString(2,ch.id);p.setString(3,Database.now());p.executeUpdate();}}audit.event("SUBSCRIPTION_ADDED",Map.of("userId",u.id(),"channelId",ch.id));return Map.of("channelId",ch.id,"channelName",ch.name);}
 @PatchMapping("/subscriptions/{id}") void patchSub(HttpServletRequest r,@PathVariable long id,@RequestBody Map<String,Object>b)throws Exception{var u=user(r);boolean enabled=Boolean.TRUE.equals(b.get("enabled"));try(Connection c=db.open();PreparedStatement p=c.prepareStatement("UPDATE youtube_subscriptions SET enabled=? WHERE id=? AND user_id=?")){p.setInt(1,enabled?1:0);p.setLong(2,id);p.setLong(3,u.id());if(p.executeUpdate()==0)throw new ResponseStatusException(HttpStatus.NOT_FOUND);}audit.event("SUBSCRIPTION_UPDATED",Map.of("userId",u.id(),"subscriptionId",id,"enabled",enabled));}
 @DeleteMapping("/subscriptions/{id}") void delSub(HttpServletRequest r,@PathVariable long id)throws Exception{var u=user(r);if(!syncer.removeSubscription(u.id(),id))throw new ResponseStatusException(HttpStatus.NOT_FOUND);audit.event("SUBSCRIPTION_REMOVED",Map.of("userId",u.id(),"subscriptionId",id)); }
 @PostMapping("/subscriptions/{id}/refresh") Map<String,Object> refresh(HttpServletRequest r,@PathVariable long id)throws Exception{var u=user(r);String channel;try(Connection c=db.open();PreparedStatement p=c.prepareStatement("SELECT channel_id FROM youtube_subscriptions WHERE id=? AND user_id=? AND enabled=1")){p.setLong(1,id);p.setLong(2,u.id());ResultSet x=p.executeQuery();if(!x.next())throw new ResponseStatusException(HttpStatus.NOT_FOUND);channel=x.getString(1);}audit.event("SUBSCRIPTION_REFRESH_STARTED",Map.of("userId",u.id(),"subscriptionId",id,"channelId",channel));int n=syncer.sync(channel,u.id());audit.event("SUBSCRIPTION_REFRESH_COMPLETED",Map.of("userId",u.id(),"subscriptionId",id,"channelId",channel,"discovered",n));return Map.of("discovered",n);}
 @GetMapping("/videos") List<Map<String,Object>> videos(HttpServletRequest r)throws Exception{var u=user(r);return rows("SELECT v.video_id,v.title,v.description,v.published_at,v.duration_seconds,c.name AS channel,uv.library_path,COALESCE(e.status,'NOT_CACHED') AS cache_status,e.last_accessed_at AS cache_last_accessed_at,CASE WHEN e.last_accessed_at IS NULL THEN NULL ELSE datetime(e.last_accessed_at, '+' || COALESCE((SELECT value FROM settings WHERE key='cache_retention_days'),'30') || ' days') END AS cache_expires_at,COALESCE((SELECT SUM(f.size_bytes) FROM cached_fragments f WHERE f.video_id=v.video_id),0) AS cache_bytes,COALESCE((SELECT COUNT(*) FROM cached_fragments f WHERE f.video_id=v.video_id AND f.completed=1),0) AS cached_fragments,CASE WHEN e.status='COMPLETE' THEN 1 ELSE 0 END AS downloaded FROM user_videos uv JOIN videos v ON v.video_id=uv.video_id JOIN youtube_channels c ON c.channel_id=v.channel_id LEFT JOIN cache_entries e ON e.video_id=v.video_id WHERE uv.user_id=? ORDER BY v.published_at DESC",u.id());}
 @GetMapping("/admin/settings") Map<String,String> settings(HttpServletRequest r)throws Exception{admin(r);return db.settings(true);}
 @PatchMapping("/admin/settings") void settings(HttpServletRequest r,@RequestBody Map<String,String>b)throws Exception{var u=admin(r);try{SettingsPolicy.validate(b);}catch(IllegalArgumentException e){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,e.getMessage());}for(var e:b.entrySet()){if(e.getValue()==null||e.getValue().isBlank()||SettingsPolicy.MASK.equals(e.getValue()))continue;db.saveSetting(e.getKey(),e.getValue(),SettingsPolicy.isSecret(e.getKey()));}audit.event("ADMIN_SETTING_CHANGED",Map.of("userId",u.id(),"settingCount",b.size()));}
 @GetMapping("/admin/users") List<Map<String,Object>> users(HttpServletRequest r)throws Exception{admin(r);return rows("SELECT id,username,email,role,filesystem_slug,created_at FROM users ORDER BY username");}
 @PatchMapping("/admin/users/{id}") void userPatch(HttpServletRequest r,@PathVariable long id,@RequestBody Map<String,String>b)throws Exception{var u=admin(r);String role=req(b,"role");if(!Set.of("USER","ADMIN").contains(role))throw new ResponseStatusException(HttpStatus.BAD_REQUEST);try(Connection c=db.open();PreparedStatement p=c.prepareStatement("UPDATE users SET role=?,updated_at=? WHERE id=?")){p.setString(1,role);p.setString(2,Database.now());p.setLong(3,id);if(p.executeUpdate()==0)throw new ResponseStatusException(HttpStatus.NOT_FOUND);}audit.event("ADMIN_USER_ROLE_CHANGED",Map.of("adminId",u.id(),"targetUserId",id,"role",role));}
 @GetMapping("/admin/cache") List<Map<String,Object>> cache(HttpServletRequest r)throws Exception{admin(r);return rows("SELECT video_id,format_key,status,last_accessed_at,active_readers,active_writers FROM cache_entries ORDER BY last_accessed_at");}
 @DeleteMapping("/admin/cache/{video}") void deleteCache(HttpServletRequest r,@PathVariable String video)throws Exception{var u=admin(r);try(Connection c=db.open();PreparedStatement q=c.prepareStatement("SELECT path FROM cached_fragments WHERE video_id=?")){q.setString(1,video);ResultSet x=q.executeQuery();while(x.next())Files.deleteIfExists(Path.of(x.getString(1)));try(PreparedStatement d=c.prepareStatement("DELETE FROM cached_fragments WHERE video_id=?")){d.setString(1,video);d.executeUpdate();}try(PreparedStatement d=c.prepareStatement("DELETE FROM cache_entries WHERE video_id=? AND active_readers=0 AND active_writers=0")){d.setString(1,video);d.executeUpdate();}}audit.event("CACHE_ENTRY_DELETED",Map.of("adminId",u.id(),"videoId",video));}
 @GetMapping("/admin/jobs") List<Map<String,Object>> jobs(HttpServletRequest r)throws Exception{admin(r);return rows("SELECT id,video_id,status,priority,created_at,error,type,requested_fragment,completed_fragments,total_fragments,cancel_requested,started_at,updated_at,completed_at FROM jobs ORDER BY created_at DESC");}
 @PostMapping("/admin/jobs/{id}/cancel") void cancelJob(HttpServletRequest r,@PathVariable String id)throws Exception{var u=admin(r);if(filler.cancel(id)){audit.event("BACKGROUND_JOB_CANCELLED",Map.of("adminId",u.id(),"jobId",id));return;}throw new ResponseStatusException(HttpStatus.NOT_FOUND);}
 @GetMapping("/admin/jellyfin/status") Map<String,Object> jellyfinStatus(HttpServletRequest r){var u=admin(r);Map<String,Object> value=jellyfin.adminStatus();audit.event("JELLYFIN_STATUS_CHECKED",Map.of("adminId",u.id(),"reachable",value.getOrDefault("reachable",false)));return value;}
 @PostMapping("/admin/jellyfin/validate") Map<String,Object> jellyfinValidate(HttpServletRequest r){var u=admin(r);Map<String,Object> value=jellyfin.adminStatus();audit.event("JELLYFIN_VALIDATED",Map.of("adminId",u.id(),"reachable",value.getOrDefault("reachable",false)));return value;}
 @PostMapping({"/admin/jellyfin/refresh","/admin/jellyfin/sync"}) Map<String,Object> jellyfinRefresh(HttpServletRequest r){var u=admin(r);Map<String,Object> value=jellyfin.refreshNow();audit.event("JELLYFIN_REFRESH_REQUESTED",Map.of("adminId",u.id(),"success",value.getOrDefault("success",false)));return value;}
 private record Channel(String id,String name,String url){}
 private Channel resolve(String raw)throws Exception {String id=raw.matches("UC[A-Za-z0-9_-]{20,}")?raw:null;String key=db.settings(false).get("youtube_api_key");if(key==null||key.isBlank())throw new ResponseStatusException(HttpStatus.PRECONDITION_REQUIRED,"administrator must configure YouTube Data API key");String endpoint=id!=null?"https://www.googleapis.com/youtube/v3/channels?part=snippet&id="+id+"&key="+URLEncoder.encode(key,java.nio.charset.StandardCharsets.UTF_8):"https://www.googleapis.com/youtube/v3/search?part=snippet&type=channel&maxResults=1&q="+URLEncoder.encode(raw,java.nio.charset.StandardCharsets.UTF_8)+"&key="+URLEncoder.encode(key,java.nio.charset.StandardCharsets.UTF_8);var root=new com.fasterxml.jackson.databind.ObjectMapper().readTree(HttpClient.newHttpClient().send(HttpRequest.newBuilder(URI.create(endpoint)).GET().build(),HttpResponse.BodyHandlers.ofString()).body());if(!root.path("items").isArray()||root.path("items").isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND,"channel not found");var x=root.path("items").get(0);String cid=id!=null?x.path("id").asText():x.path("id").path("channelId").asText();return new Channel(cid,x.path("snippet").path("title").asText(),"https://www.youtube.com/channel/"+cid);}
 static String req(Map<String,String>b,String k){if(b.get(k)==null||b.get(k).isBlank())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,k+" is required");return b.get(k);}
 List<Map<String,Object>> rows(String sql,Object... args)throws Exception{List<Map<String,Object>> all=new ArrayList<>();try(Connection c=db.open();PreparedStatement p=c.prepareStatement(sql)){for(int i=0;i<args.length;i++)p.setObject(i+1,args[i]);ResultSet r=p.executeQuery();var md=r.getMetaData();while(r.next()){Map<String,Object> m=new LinkedHashMap<>();for(int i=1;i<=md.getColumnCount();i++)m.put(md.getColumnLabel(i),r.getObject(i));all.add(m);}}return all;}
 void cookie(HttpServletResponse r,String token){r.addHeader(HttpHeaders.SET_COOKIE,ResponseCookie.from("FT_SESSION",token).httpOnly(true).secure(cookieSecure).sameSite("Lax").path("/").maxAge(java.time.Duration.ofDays(14)).build().toString());}
 void clearCookie(HttpServletResponse r){r.addHeader(HttpHeaders.SET_COOKIE,ResponseCookie.from("FT_SESSION","").httpOnly(true).secure(cookieSecure).sameSite("Lax").path("/").maxAge(java.time.Duration.ZERO).build().toString());}
}
